[WIP] Adding the ability to optionally change the CSS class(es) applied to …
openshift/registry-image-widgets pull request #18
Opened 2017-08-02 20:54 UTC by rhamilto

…registry-imagestream-listing so that Bootstrap/PatternFly styles can be used instead of the default.  This is so that in the context of origin-web-console, registry-imagestream-listing can have similar styling to the tables used throughout origin-web-console.  Note:  a few additional overrides are required in origin-web-console, but those will be added in the PR that consumes the changes in this PR.

![screen shot 2017-08-02 at 4 50 12 pm](https://user-images.githubusercontent.com/895728/28894429-dd764374-77a2-11e7-8161-72aaddb24d26.PNG)

2017-08-03 08:23 UTC, stefwalter commented
@petervo Could you review this?

@spadgett Could you add petervo and @thomasmckay as contributors so we can request reviews in the sidebar?

2017-08-03 13:12 UTC, petervo requested changes

2017-08-03 13:12 UTC, petervo commented on views/imagestream-listing.html
> +<table ng-class="classNames ? '{{classNames}}' : 'listing-ct'">
I think a lot of other styles in here that you probably want to keep reference listing-ct. Either those need to change, or this should keep listing-ct even when classNames is present.

2017-08-03 13:18 UTC, spadgett commented
> @spadgett Could you add petervo and @thomasmckay as contributors so we can request reviews in the sidebar?

@dobbymoodge Can you help with this?

2017-08-03 13:27 UTC, spadgett commented
@stefwalter @petervo Is there a reason we're not just the Patternfly table styles directly in the widgets?

2017-08-03 18:15 UTC, petervo commented
@spadgett because that would totally break the styling in the registry. Alternative to this is to remove the table tag from the widget and make these directives

```
restrict: 'A',
```

instead of 'E'. Then each project can add their own table classes.

2017-08-17 15:26 UTC, rhamilto commented on views/imagestream-listing.html
> +<table ng-class="classNames ? '{{classNames}}' : 'listing-ct'">
listing-ct can still be passed in as an optional class.  In the origin-web-console, the listing-ct classes actually break our desired layout, hence this approach; this gives the consumers of the repo direct control over which styles are used while maintaining backward compatibility.

2017-08-18 18:36 UTC, petervo commented on views/imagestream-listing.html
> +<table ng-class="classNames ? '{{classNames}}' : 'listing-ct'">
@rhamilto have you actually tried it? For me without the class a bunch of other styles don't apply. Is the plan to just have overrides there?

2017-08-18 20:06 UTC, rhamilto commented on views/imagestream-listing.html
> +<table ng-class="classNames ? '{{classNames}}' : 'listing-ct'">
I have.  The [screenshot above](https://github.com/openshift/registry-image-widgets/pull/18#issue-247518924) utilizes the change in the context of origin-web-console.  In the case of the console, we appear to not be utilizing all of the functionality of the directive, so it's not a problem.  My ultimate aim is to simply fix https://github.com/openshift/origin-web-console/issues/1849, which this change enables.

2017-09-05 18:39 UTC, closed without merging